config/routes.rb
Demoapp::Application.routes.draw do
  devise_for :members

  

  resources :users
resources :questions do
	resources :answers
end

  root :to => 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/question.rb
class Question < ActiveRecord::Base
has_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
 
  # Setup accessible (or protected) attributes for your model
 
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
before_filter :find_question
before_filter :find_ans,:only => [:show]
def index
	@answer=@question.Answer.all
end
	def new
	@answer=@question.answers.new
	end
	def create
    @answer = @question.answers.build(params[:answer])
    if @answer.save
      flash[:notice] = "Ticket has been created."
      redirect_to [@question, @answer]
    else
      flash[:alert] = "Ticket has not been created."
      render :action => "new"
    end
    def show
    	 
    end
  end
	  private
    def find_question
      @question = Question.find(params[:question_id])
      # @question = Question.find(params[:comment])
    end
    def find_ans
    @answer = @question.answers.find(params[:id])
    	 logger.warn("==========#{@answer.inspect}")
    	 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
 
 # before_filter :set_current_user  
 # before_filter :login_required
  protected
  def set_current_user
    if session[:user_id] 
           @current_user = User.find(session[:user_id])
       else
           @current_user = nil
       end
  end

  			def authenticate_user!
  			if @current_user.nil?
		    flash[:alert] = "You must be an admin to do that."
    		redirect_to root_path
  		end
	end
	
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	def index
		@question=Question.all
		@member = Member.find(:all)
		respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @question }
    end
	end

	def new
		@question=Question.new
	end
	def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end
	def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'User was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
 
  def index
    @users = User.all
@member = Member.find(:all)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_for [ @question, @answer ] do |f| %>

  <p>
    <label>comment</label>
    <%= f.text_area :comment%>
  </p>
  <%= f.submit %>
<% end %>

app/views/answers/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/answers/show.html.erb
<p>
  <b>Answer:</b>
  <%= @answer.comment %>
  </p>





<%= link_to 'Back', questions_path %>

app/views/common/_footer.html.erb
<%= link_to "Contact US", root_path %>

app/views/common/_header.html.erb
<div style="float:left;font-size: 20pt; font-family: verdana;line-height: 30px;"><%= link_to "Home", root_path %></div>
<div class="subnav" style=" font-size: 20pt; font-family: verdana; line-height: 30px;"> 
  <% if member_signed_in? %>
     <div class="page-header" style="padding-left:700px;">  Signed in as <%= current_member.email %>
     <%= link_to "Sign out",destroy_member_session_path,:method => :delete %>
  <% else %>
    <div class="page-header" style="padding-left:1000px;">  <%= link_to "Sign up",new_member_registration_path %> or <%= link_to "Sign in", new_member_session_path %></div> 
   <% end %>
</div>
      
      
      

app/views/common/_tab.html.erb
<div class="page-header" style="text-align:center;">
<div class="btn btn-primary btn-large">Ruby on Rails</div>
<div class="btn btn-success btn-large">PHP</div>
<div class="btn btn-warning btn-large">C/C++</div>
<div class="btn btn-danger btn-large">.NET</div>
<div class="btn btn-inverse btn-large">Android</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demoapp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial=>'common/header' %>
<%= yield %>
<div class="modal-footer" style="margin-bottom:20px;">
<%= render :partial=>'common/footer' %>
</div>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label>Question  </label>
    <%= f.text_field :name %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/index.html.erb
<% if current_member %>
<%= render :partial=>'common/tab' %>

<table>
  <tr>
    <th>Question</th>
   
  </tr>

<% @question.each do |question| %>
  <tr>
    <td><%= question.name %></td>
    <td><%= link_to 'Show', question %></td>
  </tr>
<% end %>
</table>

<br />

<%#= link_to 'Answer',question_answers_path(@question)%>
<%= link_to 'Create Question', new_question_path %>
<% else %>
<br><br><br><br><br><br>

<h2 class="alert alert-success "style="border:medium solid;"><div class="btn-inverse btn-large" style="padding-top:100px;padding-bottom:100px;font-size:30pt;border:medium solid;"><marquee>QUESTION ANSWER SYSTEM</marquee></div></h2>
<br><br><br><br><br><br>
<% end %>

app/views/questions/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p>
  <b>Question:</b>
  <%= @question.name %>
  </p>




<%= link_to 'Answer', new_question_answer_path(@question)%>
<%= link_to 'Back', questions_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% if current_member %>
<%= render :partial=>'common/tab' %>
<h1>Listing users</h1>

</div>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>
<% else %>
<br><br><br><br><br><br>

<h2 ><div class="alert alert-success" style="text-align: center;padding-top:100px;padding-bottom:100px;padding-left:150px;font-size:30pt;">WELCOME TO STACK OVERFLOW<div></h2>
<br><br><br><br><br><br>
<% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>